name: contribution
author: valory
version: 0.1.0
description: A service that tracks the community members' points and updates their
  NFTs autonomously
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiaeysyipptsieavfpyfkrfl3n37klu3ux7o2rtks2w4k2nnr2hshu
fingerprint_ignore_patterns: []
agent: valory/contribution:0.1.0:bafybeihnwlz6ulfgupgz6wnoymi2a7xwgjyfluja6xha5qhooeinraisbe
number_of_agents: 1
---
public_id: valory/contribution_skill_abci:0.1.0
type: skill
models:
  params:
    args:
      broadcast_to_server: true
      history_end: null
      ipfs_domain_name: /dns/registry.autonolas.tech/tcp/443/https
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${SERVICE_CONTRIBUTION_RPC:str:http://host.docker.internal:8545}
      chain_id: 31337
      poa_chain: false
      default_gas_price_strategy: eip1559
