name: contribution
author: valory
version: 0.1.0
description: A service that tracks the community members' points and updates their
  NFTs autonomously
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiaeysyipptsieavfpyfkrfl3n37klu3ux7o2rtks2w4k2nnr2hshu
fingerprint_ignore_patterns: []
agent: valory/contribution:0.1.0:bafybeibelny6qrtqwlpubvgipeiieythg7p2xe4k7vjzcbwkphcgybqjiq
number_of_agents: 4
---
public_id: valory/contribution_abci:0.1.0
type: skill
models:
  params:
    args:
      broadcast_to_server: true
      dynamic_contribution_contract_address: ${DYNAMIC_CONTRIBUTION_CONTRACT_ADDRESS:str:0x5FbDB2315678afecb367f032d93F642f64180aa3}
      earliest_block_to_monitor: ${EARLIEST_BLOCK_TO_MONITOR:int:8053690}
      history_end: null
      ipfs_domain_name: /dns/registry.autonolas.tech/tcp/443/https
      ipfs_gateway_base_url: ${IPFS_GATEWAY_BASE_URL:str:https://gateway.staging.autonolas.tech/ipfs/}
      leaderboard_api_key: ${LEADERBOARD_API_KEY:str:null}
      leaderboard_base_endpoint: ${LEADERBOARD_BASE_ENDPOINT:str:https://sheets.googleapis.com/v4/spreadsheets}
      leaderboard_layers_range: ${LEADERBOARD_LAYERS_RANGE:str:Layers!B1:Z3}
      leaderboard_points_range: ${LEADERBOARD_POINTS_RANGE:str:Ranking!B2:C302}
      leaderboard_sheet_id: ${LEADERBOARD_SHEET_ID:str:1m7jUYBoK4bFF0F2ZRnT60wUCAMWGMJ_ZfALsLfW5Dxc}
      observation_interval: ${OBSERVATION_INTERVAL:int:300}
      share_tm_config_on_startup: ${USE_ACN:bool:false}
      token_uri_base: ${TOKEN_URI_BASE:str:https://pfp.staging.autonolas.tech/}
      consensus:
        max_participants: 4
      setup:
        all_participants: ${ALL_PARTICIPANTS:list:'[["0x976EA74026E726554dB657fA54763abd0C3a0aa9","0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65","0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc","0x14dC79964da2C08b23698B3D3cc7Ca32193d9955"]]'}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${ETHEREUM_LEDGER_RPC:str:http://host.docker.internal:8545}
      chain_id: ${ETHEREUM_LEDGER_CHAIN_ID:int:31337}
      poa_chain: ${ETHEREUM_LEDGER_IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${ETHEREUM_LEDGER_PRICING:str:eip1559}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${ACN_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
